export default [
  {
    id: 1,
    cafe_name: "Baker and Cook",
    address: "Greenwood",
    opening_time: "9:18 AM",
    closing_time: "4:23 PM",
    wifi: true,
    power: false,
    coffee_price: 2368.51,
    phone: 432,
    image: "/bandc.jpeg",
    favourite: false,
    area: "Bukit Timah",
    description: "wifi password is passion88"
  },
  {
    id: 2,
    cafe_name: "The Living Cafe",
    address: "Bukit Timah Road",
    opening_time: "9:13 AM",
    closing_time: "6:10 PM",
    wifi: true,
    power: true,
    coffee_price: 5282.49,
    phone: 4766,
    image: "/2.jpeg",
    favourite: false,
    area: "Bukit Timah",
    description: "wifi Singtel-c6v4, password 38nrwxv9dt"
  },
  {
    id: 3,
    cafe_name: "Bearded Bella",
    address: "Greenwood",
    opening_time: "9:07 AM",
    closing_time: "7:54 PM",
    wifi: true,
    power: true,
    coffee_price: 6963.69,
    phone: 1115,
    image: "/3.jpeg",
    favourite: false,
    area: "Bukit Timah",
    description: "loud music"
  },
  {
    id: 4,
    cafe_name: "Grids Coffee",
    address: "10th Floor",
    opening_time: "8:29 AM",
    closing_time: "8:09 PM",
    wifi: true,
    power: true,
    coffee_price: 308.11,
    phone: 1655,
    image: "/4.jpeg",
    favourite: false,
    area: "CBD",
    description: "co working F&B deal available"
  },
  {
    id: 5,
    cafe_name: "Atlas Coffeehouse",
    address: "Apt 1924",
    opening_time: "9:34 AM",
    closing_time: "4:38 PM",
    wifi: true,
    power: true,
    coffee_price: 4293.3,
    phone: 6236,
    image: "/5.jpeg",
    favourite: false,
    area: "Bukit Timah",
  },
  {
    id: 6,
    cafe_name: "The Book Cafe",
    address: "PO Box 79689",
    opening_time: "10:28 AM",
    closing_time: "5:43 PM",
    wifi: true,
    power: false,
    coffee_price: 541.74,
    phone: 6241,
    image: "/6.jpeg",
    new: true,
    favourite: false,
    area: "CBD",
  },
  {
    id: 7,
    cafe_name: "Craftsman Coffee",
    address: "Greenwood",
    opening_time: "10:49 AM",
    closing_time: "4:10 PM",
    wifi: true,
    power: true,
    coffee_price: 2579.21,
    phone: 6788,
    image: "/7.jpeg",
    new: true,
    favourite: false,
    area: "Bukit Timah",
  },
  {
    id: 8,
    cafe_name: "Common Man Roasters",
    address: "Quayside Isle",
    opening_time: "8:23 AM",
    closing_time: "8:29 PM",
    wifi: true,
    power: false,
    coffee_price: 6925.66,
    phone: 4083,
    image: "/8.jpeg",
    favourite: false,
    area: "Sentosa",
  },
  {
    id: 9,
    cafe_name: "The Dempsey Project",
    address: "Dempsey",
    opening_time: "8:33 AM",
    closing_time: "5:08 PM",
    wifi: true,
    power: true,
    coffee_price: 3764.73,
    phone: 6333,
    image: "/9.jpeg",
    favourite: false,
    area: "Dempsey",
    description: "loud music"
  },
  {
    id: 10,
    cafe_name: "Da Paolo",
    address: "Dempsey",
    opening_time: "10:23 AM",
    closing_time: "7:06 PM",
    wifi: true,
    power: false,
    coffee_price: 1213.51,
    phone: 5172,
    image: "/10.jpeg",
    recently_visited: true,
    favourite: false,
    area: "Dempsey",
  },
  {
    id: 11,
    cafe_name: "SPRMRKT",
    address: "Dempsey Hill",
    opening_time: "9:20 AM",
    closing_time: "5:45 PM",
    wifi: true,
    power: false,
    coffee_price: 6635.79,
    phone: 551,
    image: "/11.jpeg",
    new: true,
    favourite: false,
    area: "Dempsey",
    description: "wifi Singtel RG3D, password ewa7aer9ea"
  },
  {
    id: 12,
    cafe_name: "Relish",
    address: "Cluny Court",
    opening_time: "10:25 AM",
    closing_time: "6:17 PM",
    wifi: true,
    power: false,
    coffee_price: 4440.61,
    phone: 4654,
    image: "/12.jpeg",
    favourite: false,
    area: 'Bukit Timah'
  },
  {
    id: 13,
    cafe_name: "Simply Bread",
    address: "Cluny Court",
    opening_time: "8:24 AM",
    closing_time: "6:58 PM",
    wifi: true,
    power: false,
    coffee_price: 2174.65,
    phone: 3209,
    image: "/13.jpeg",
    favourite: false,
    area: "Bukit Timah",
    description: "natural light, gets crowded during lunchtime"
  },
  {
    id: 14,
    cafe_name: "McDonald's Ridout Tea Garden",
    address: "17th Floor",
    opening_time: "10:17 AM",
    closing_time: "4:14 PM",
    wifi: true,
    power: true,
    coffee_price: 2870.99,
    phone: 1659,
    image: "/14.jpeg",
    favourite: false,
    area: "Queensway"
  },
  {
    id: 15,
    cafe_name: "Tiong Hoe",
    address: "PO Box 2799",
    opening_time: "8:01 AM",
    closing_time: "5:30 PM",
    wifi: false,
    power: false,
    coffee_price: 6166.15,
    phone: 608,
    image: "/15.jpeg",
    favourite: false,
    area: "Queensway"
  },
  {
    id: 16,
    cafe_name: "The RITUAL",
    address: "6th Floor",
    opening_time: "10:53 AM",
    closing_time: "8:32 PM",
    wifi: true,
    power: true,
    coffee_price: 4865.48,
    phone: 4723,
    image: "/16.jpeg",
    favourite: false,
    area: "Bukit Timah",
    description: "wifi password is themomentisnow"

  },
  {
    id: 17,
    cafe_name: "Baker & Cook Dempsey",
    address: "Dempsey",
    opening_time: "8:00 AM",
    closing_time: "10:00 PM",
    wifi: true,
    power: false,
    coffee_price: 5863.81,
    phone: 588,
    image: "/17.jpeg",
    favourite: false,
    area: "Dempsey"
  },
  {
    id: 18,
    cafe_name: "Thus Coffee",
    address: "Suite 74",
    opening_time: "9:00 AM",
    closing_time: "9:00 PM",
    wifi: false,
    power: false,
    coffee_price: 6244.33,
    phone: 3282,
    image: "/18.jpeg",
    favourite: false,
    area: "Serangoon"
  },
  {
    id: 19,
    cafe_name: "Apt 536",
    address: "Suite 62",
    opening_time: "10:45 AM",
    closing_time: "8:43 PM",
    wifi: true,
    power: false,
    coffee_price: 1116.28,
    phone: 2818,
    image: "/19.jpeg",
    favourite: false,
  },
  {
    id: 20,
    cafe_name: "Apt 509",
    address: "5th Floor",
    opening_time: "10:38 AM",
    closing_time: "6:34 PM",
    wifi: false,
    power: true,
    coffee_price: 5611.58,
    phone: 2667,
    image: "/20.jpeg",
    favourite: false,
  },
];
